#!/bin/bash

export XDG_CONFIG_HOME=$HOME/.config; mkdir $XDG_CONFIG_HOME
export XDG_CACHE_HOME=$HOME/.cache; mkdir $XDG_CACHE_HOME
export XDG_DATA_HOME=$HOME/.local/share; mkdir $XDG_DATA_HOME
export XDG_STATE_HOME=$HOME/.local/state; mkdir $XDG_STATE_HOME
export ZDOTDIR=$XDG_CONFIG_HOME/zsh; mkdir $ZDOTDIR

mkdir -p $XDG_DATA_HOME/vim/backup $XDG_DATA_HOME/vim/swap $XDG_DATA_HOME/vim/undo $XDG_DATA_HOME/vim/view
mkdir -p $XDG_CONFIG_HOME/vim/bundle

cp -r .config $HOME
cp .zshenv $HOME

git clone https://github.com/VundleVim/Vundle.vim.git $XDG_CONFIG_HOME/vim/bundle/Vundle.vim
if [[ $? -ne 0 ]]; then; exit 1

vim +PluginInstall +qall