#!/bin/bash

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

mkdir -p $XDG_CACHE_HOME/vim/backup $XDG_CACHE_HOME/vim/swap $XDG_CACHE_HOME/vim/undo

cp -r .config $HOME
cp .zshenv $HOME


