version: '3'

services:
  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M
    volumes:
      - /srv/base/certs:/etc/nginx/certs:ro
      - /srv/base/vhost.d:/etc/nginx/vhost.d
      - /srv/base/html:/usr/share/nginx/html
      - /srv/base/config:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - external-proxy

  crypt:
    image: nginxproxy/acme-companion
    restart: always
    environment:
      - DEFAULT_EMAIL=
    volumes:
      - /srv/base/certs:/etc/nginx/certs
      - /srv/base/vhost.d:/etc/nginx/vhost.d
      - /srv/base/html:/usr/share/nginx/html
      - /srv/base/config:/etc/nginx/conf.d:ro
      - acme:/etc/acme.sh
      - /root/.secrets/google.json:/gcloud-service-account.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - external-proxy
    depends_on:
      - proxy

volumes:
  certs:
  acme:
  vhost.d:
  html:

networks:
  external-proxy:
    external: true
