syntax on
let mapleader = " "
set nocompatible
filetype indent plugin on
set number relativenumber
set laststatus=2
set noshowmode

" Set XDG directories
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

" Vundle Plugins
set rtp+=$XDG_CONFIG_HOME/vim/bundle/vundle
call vundle#rc("$XDG_CONFIG_HOME/vim/bundle")
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jiangmiao/auto-pairs'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'itchyny/lightline.vim'
call vundle#end()

" Post plugin configuration
highlight YcmErrorLine guibg=#550000
highlight SyntasticError guibg=#550000
highlight YcmWarningLine guibg=#555500
highlight SyntasticWarning guibg=#555500

" Key mappings
silent! map <F2> :NERDTreeToggle<CR>

