set nocompatible
filetype off

" Set XDG directories
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

" set the runtime path to include Vundle
" ~/.vim/bundle/Vundle.vim
set rtp+=/home/suleyk/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'ycm-core/YouCompleteMe'
call vundle#end()
filetype plugin indent on

set number relativenumber
syntax on

let mapleader = " "
call plug#begin('~/.vim/plugged')
Plug 'junegunn/goyo.vim'
Plug 'PotatoesMaster/i3-vim-syntax'
call plug#end()

set laststatus=2
set noshowmode

" Key mappings
silent! map <F2> :NERDTreeToggle<CR>

