services:
  apache:
    image: 'bitnami/apache:latest'
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    volumes:
      - /srv/httpd/data:/app
      - /etc/localtime:/etc/localtime:ro
    networks:
      - external-proxy
networks:
  external-proxy:
    external: true
