version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - 5555:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/base/portainer:/data
    networks:
      - internal
        # TODO: Setup an internal ssl

networks:
  internal:
    external: true
