version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /srv/prd/cloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env
    networks:
      - nextcloud-internal

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud-internal

  app:
    build: .
    image: nextcloud:apache
    restart: always
    volumes:
      - /srv/prd/cloud/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - nextcloud-proxy
      - nextcloud-internal

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - /srv/prd/cloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nextcloud-internal

volumes:
  db:
  
networks:
  nextcloud-proxy:
    external: true
  nextcloud-internal:
    external: true
