version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /srv/cloud/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: redis-server --save 20 1 --loglevel warning --requirepass 70DF6DB40896D9BAB1E83700B93C04A1
    networks:
      - internal

  webapp:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - /srv/cloud/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_HOST=
      - MYSQL_PASSWORD=
      - REDIS_HOST=
      - REDIS_PASSWORD=
    depends_on:
      - db
      - redis
    networks:
      - external-proxy
      - internal

networks:
  external-proxy:
    external: true
  internal:
    external: true
