version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /srv/cloud/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal

  webapp:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - /srv/cloud/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - external-proxy
      - internal

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - /srv/cloud/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - internal

networks:
  external-proxy:
    external: true
  internal:
    external: true
