services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    container_name: transmission
    environments:
      - PUID=
      - PGID=
    volumes:
      - /srv/transmission/config:/config
      - /srv/transmission/downloads:/downloads
      - /srv/transmission/watch:/watch
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - internal

networks:
  internal:
    external: true
