#!/bin/sh
ROOT=$PWD/..
LOG=$HOME/build.log
USERNAME=$(whoami)
USERGRP=$(whoami)
HOME_PERMISSIONS=644

##! Initially, make sure the machine is up-to-date
##! We'll be using pacman a lot, so best to be sure the system is functioning
cd $HOME
sudo pacman -Syu --noconfirm 
if [[ "$?" == 0 ]]; then
	##! Skip the following sections after relogging
	if [[ -f $LOG ]]; then
		##! Second time running
		mkdir -p $XDG_CONFIG_HOME/neofetch
		mkdir -p $XDG_CONFIG_HOME/vim
		mkdir -p $XDG_CONFIG_HOME/zsh
		mkdir $XDG_CACHE_HOME
		mkdir -p $XDG_DATA_HOME/vim/undo
		mkdir -p $XDG_DATA_HOME/vim/backup
		mkdir -p $XDG_DATA_HOME/vim/view
		mkdir $XDG_STATE_HOME
		mkdir $HOME/git

		##! Obtain needed applications
		sudo pacman -S --needed --noconfirm i3-gaps dunst ranger vim neofetch fakeroot 

		##! Fetch and install AUR applications
		cd $HOME/git
		git clone https://aur.archlinux.org/polybar-git.git
		pushd polybar
    			makepkg -si
  		popd 
		cp -rv $ROOT/.scripts $HOME
		cp -rv $ROOT/.config $XDG_CONFIG_HOME

		##! Configure file permissions
		sudo chown -r $USERNAME $HOME
		sudo chgrp -r $USERGRP $HOME
		chmod -r $HOME_PERMISSIONS $HOME

		##! Complete, cleanup
		rm $LOG
		sudo reboot
	else
		##! First time run
		##! Set up xdg
		touch $LOG

		##! Initial application install
		sudo pacman -S --needed --noconfirm git zsh

		cp -v $ROOT/.zshenv $HOME
		chsh -s /bin/zsh
		##! Set up folder directory
		mkdir $HOME/dox
		mkdir $HOME/pix
		mkdir $HOME/vid
		mkdir $HOME/dl
		echo "Step (1/2) complete. Please relog and rerun this script"
		sleep 1
	fi
else
  echo "Failed init start"
fi
