#! /bin/sh

DATEFTM="${DATEFTM:-+%a. %d. %b. %Y}"
SHORTFMT="${SHORTFMT:-+%d.%m.%Y}"
LABEL="${LABEL:-}"
blockdate=$(date "$DATEFTM")
shortblockdate=$(date "$SHORTFMT")
BLOCK_BUTTON=1
year=$(date '+%Y')
month=$(date '+%m')
maxweeks=$((($(date -d "`date +%Y%m01` +1 month -1 day " +%d)-1)/7+2))
case "$BLOCK_BUTTON" in
    1|2)
        date=$(date '+%B %Y');;
    3)
        (( month == 12 )) && month=1 && year=$((year + 1)) || month=$((month + 1))
        date=$(cal $month $year | sed -n '1s/^  *//;1s/  *$//p')
esac
cal --color=always $month $year \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | tail -n +2 \
    | rofi \
        -dmenu \
        -markup-rows \
        -no-fullscreen \
        -font "Monospace 18" \
        -hide-scrollbar \
	-padding 2\
        -bw 2 \
        -m -3 \
	-lines "$maxweeks"\
        -theme-str '#window {anchor:northeast; location:northwest;}' \
        -eh 1 \
        -width -20 \
        -no-custom \
        -p "$date" > /dev/null 
echo "$LABEL$blockdate"
echo "$LABEL$shortblockdate"
