services:
  apache:
    image: 'bitnami/apache:latest'
    restart: always
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/prd/www:/app
    networks:
      - www-proxy

networks:
  www-proxy:
    external: true
